/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fmoddemo_EffectUtils */

#ifndef _Included_com_fmoddemo_EffectUtils
#define _Included_com_fmoddemo_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fmoddemo_EffectUtils
 * Method:    fix
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fmoddemo_EffectUtils_stop
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_fmoddemo_EffectUtils_fix
        (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
